#!/usr/bin/env node

const { parseScript } = require("shift-parser");
const query = require("shift-query");
const getStdin = require("get-stdin");

let fileContents, pattern;

let args = process.argv.slice(2);
let outputJSON = !process.stdout.isTTY;

if (args[0] === '-j') {
  outputJSON = true;
  args = args.slice(1);
};

function printUsage(code = 0) {
  console.log(`
Usage: shift-query file.js query-pattern

If a script is piped to shift-query then the first argument is treated as the query pattern
`);
  process.exit(code);
}

console.log(process.stdout.isTTY);

(async () => {
  if (process.stdin.isTTY) {
    const file = args[0];
    pattern = args[1];

    if (!file || !pattern) printUsage(1);
    try {
      fileContents = require("fs").readFileSync(file, { encoding: "utf8" });
    } catch (e) {
      console.error(`Can not read file`);
      process.exit(2);
    }
  } else {
    fileContents = await getStdin();
    pattern = args[0];
    if (!fileContents || !pattern) printUsage(1);
  }

  let ast;

  try {
    ast = parseScript(fileContents);
  } catch (e) {
    console.error(`Could not parse script: ${e.description}`);
    process.exit(3);
  }

  const result = query(ast, pattern);

  console.log(outputJSON ? JSON.stringify(result) : result);
})();
